### ISSUE TITLE
Error in opening bpch2 file

### ISSUE THREAD

**Issue by yc-chan** [barronh/pseudonetcdf#12]
Hi Barron,

I have got a bpch2 file from GEOS-CHEM simulation (MERRA MET-field , 2x2.5 degree resolution, 3 monthly-averaged diagnosis data). I want to open it in a python script (env: linux Anaconda3 -4.1.1) using pseudonetcdf. I tried the follow commands:

> from PseudoNetCDF import PNC
> import numpy as np
> import matplotlib.pyplot as plt
> 
> args = PNC("--format=bpch2,vertgrid='MERRA-NATIVE'",filename)

This is the error message I received:

> /n/home06/ychan/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/pncparse.p                                                                                                                                                          y in PNC(*args, **kwds)
>     329
>     330 def PNC(*args, **kwds):
> --> 331     ifiles, outargs = pncparse(args = args, **kwds)
>     332     outargs.ifiles = ifiles
>     333     return outargs
> 
> /n/home06/ychan/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/pncparse.p                                                                                                                                                                y in pncparse(has_ofile, plot_options, map_options, interactive, args, parser                                                                                                                                          )
>     301     for subarg in subargs:
>     302         ipaths.extend(subarg.ifile)
> --> 303         ifiles.extend(pncprep(subarg)[0])
>     304     # ifile is set to results from parsing
>     305     # this includes the standard ifile
> 
> /n/home06/ychan/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/pncparse.p                                                                                                                                                                y in pncprep(args)
>     357     #nifiles = len(args.ifile) - has_ofile
>     358     ipaths = args.ifile[:]
> --> 359     fs = getfiles(ipaths, args)
>     360     fs = subsetfiles(fs, args)
>     361     fs = seqpncbo(args.operators, fs, coordkeys = args.coordkeys)
>   ........................................
> OSError: Unable to open path with bpch2(path, **{'vertgrid': 'MERRA-NATIVE'})
>         path=filename
>         error="could not broadcast input array from shape (72) into shape (73                                                                                                                                               )"

I presume the no. of vertical layer should be 72 in my file so I feel strange about the number 73.
Do you know what happens here?

Anyway, thanks for this nice project!

-Yuk Chun

**Comment by barronh** [comment]
The number of vertical layers is 72, but the number of interfaces is 73. The bpch and bpch2 readers create meta-variables that describe the coordinate space, including vertical hybrid coordinates.

I think the problem is that the bpch2 has a few GEOS-5-REDUCED hard codes that were never updated (bpch2 is less mature than bpch). In PseudoNetCDF/geoschemfiles/_newbpch.py try replacing "layer47" with "layer" and "layer48" with "layer_bounds".

If that doesn't work, post a file that I can test on an ftp server. I will figure it out faster than going back and forth.

**Comment by yc-chan** [comment]
It doesn't work.
I have sent the link of a sample file to your uni email address.

**Comment by barronh** [comment]
The attached diff shows how to fix _newbpch.py. The only critical change is on line 236 where
"max(levels)" becomes "min(max(levels), self.Ap.size - 1)"

It turns out that one of your diagnostics (PEDGE-$_PSURF) is output on the interfaces, which creates a 73 level variable. Thus we must output check that the default "layer" is never more than the mid levels.

Please confirm that it works and then I will patch the master branch.

[newbpch.patch.txt](https://github.com/barronh/pseudonetcdf/files/382869/newbpch.patch.txt)

**Comment by yc-chan** [comment]
It works now.
Thanks for the really prompt reply!
